name: covid_go_cek_in
description: Application for check and tracking during covid 19 outbreak
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  double_back_to_close_app: ^2.1.0
  barcode_scan: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/img/icon.png"
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/img/avatar/
  fonts:
    - family: Lato
      fonts:
        - asset: assets/font/Lato-Regular.ttf