name: covid_go_cek_in
description: Application for check and tracking during covid 19 outbreak
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  double_back_to_close_app: ^2.1.0
  flutter_barcode_scanner: ^2.0.0
  http: ^0.13.4
  intl: ^0.17.0
  crypto : ^3.0.1
  shared_preferences: ^2.0.13
  syncfusion_flutter_datepicker: ^20.1.48
  flutter_datetime_picker: ^1.5.0
  firebase_core: ^1.17.1
  firebase_core_web: ^1.6.4
  firebase_messaging: ^11.4.1
  flutter_local_notifications: ^9.5.3+1
  sqflite: ^2.0.2+1

dev_dependencies:
  flutter_lints: ^2.0.0
  test: ^1.21.1
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.3

flutter_icons:
  image_path: "assets/icon/icon.png"
  ios: true
  android: true
  

flutter:
  uses-material-design: true
  assets:
    - assets/img/
  fonts:
    - family: Lato
      fonts:
        - asset: assets/font/Lato-Regular.ttf